version: 2
jobs:
  build:
    - image: circleci/python:2.0
    #machine:
      #enabled: true
    working_directory: ~/S3ContinuousDeploy
    steps:
      - checkout
      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
          command: 'aws s3 sync https://github.com/toopukondabhaskar/S3ContinuousDeploy s3://s3awscirclecidemo --region us-east-1'
  #deploy:
    #machine:
      #enabled: true
    #working_directory: ~/S3ContinuousDeploy
    #steps:
       #- run:
         # name: Deploy
          #command: 'aws s3 sync ${source}/ s3://${bucket} --region us-west-2'
          #command: 'aws s3 sync https://github.com/toopukondabhaskar/S3ContinuousDeploy s3://s3awscirclecidemo --region us-east-1'
