version: 2
jobs:
  build:
    docker:
      - image: bash:4.4.19
      #- image: circleci/redis:4.0
    #machine:
      #enabled: true
    working_directory: ~/tmp
    steps:
      - checkout
      - run:
          apt-get update && apt-get install -y awscli
          #name: install AWS CLI (first install pip, the Python package manager)
          #command: | 
            #apt-get update && apt-get install -y awscli 
            #apk add --update python python-dev py-pip build-base
            #pip install awscli
          #command: 'aws s3 sync https://github.com/toopukondabhaskar/S3ContinuousDeploy s3://s3awscirclecidemo --region us-east-1'
  #deploy:
    #machine:
      #enabled: true
    #working_directory: ~/S3ContinuousDeploy
    #steps:
       #- run:
         # name: Deploy
          #command: 'aws s3 sync ${source}/ s3://${bucket} --region us-west-2'
          #command: 'aws s3 sync https://github.com/toopukondabhaskar/S3ContinuousDeploy s3://s3awscirclecidemo --region us-east-1'
