version: 2
jobs:
  build:
    docker:
      #- image: circleci/ruby:2.4
      #- image: circleci/redis:4.0
    machine:
      enabled: true
    working_directory: ~/tmp/S3ContinuousDeploy
    steps:
      - checkout
      - run:
          command: | 
            #mkdir /home/circleci/artifact && cd /home/circleci/artifact
            #zip -r artifact.zip   ~/tmp/S3ContinuousDeploy/*
            cd ~/tmp/S3ContinuousDeploy/;  zip -r file *
            sudo apt-get update && sudo apt-get install nginx -y    
      - run: 
          sudo pip install awscli
      - run: 
           aws s3 sync file.zip s3://s3awscirclecidemo --delete
          #name: install AWS CLI (first install pip, the Python package manager)
          #command: | 
            #apt-get update && apt-get install -y awscli 
            #apk add --update python python-dev py-pip build-base
            #pip install awscli
          #command: 'aws s3 sync S3ContinuousDeploy s3://s3awscirclecidemo --delete'
  #deploy:
    #machine:
      #enabled: true
    #working_directory: ~/S3ContinuousDeploy
    #steps:
       #- run:
         # name: Deploy
          #command: 'aws s3 sync ${source}/ s3://${bucket} --region us-west-2'
          #command: 'aws s3 sync https://github.com/toopukondabhaskar/S3ContinuousDeploy s3://s3awscirclecidemo --region us-east-1'
