version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
      #- image: circleci/redis:4.0
    #machine:
      #enabled: true
    working_directory: ~/tmp/S3ContinuousDeploy
    steps:
      - checkout
      - run: cd ~/tmp/S3ContinuousDeploy/; zip -r ../zipped_dir3.zip *
  
  compress:
    machine:
      enabled: true
    working_directory: ~/tmp/S3ContinuousDeploy
    steps:
      - checkout
      - run:
          command: |
            cd ~/tmp/S3ContinuousDeploy/; zip -r ../zipped_dir3.zip *
            sudo apt-get update && sudo apt-get install nginx -y
      - run:
          sudo pip install awscli
      - run:
           aws s3 sync ~/tmp s3://s3awscirclecidemo --delete
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            bash vendor/bin/awscodedeploy.sh
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - compress
      - deploy

  #deploy:
    #machine:
      #enabled: true
    #working_directory: ~/S3ContinuousDeploy
    #steps:
       #- run:
         # name: Deploy
          #command: 'aws s3 sync ${source}/ s3://${bucket} --region us-west-2'
          #command: 'aws s3 sync https://github.com/toopukondabhaskar/S3ContinuousDeploy s3://s3awscirclecidemo --region us-east-1'
